Add File API
fuzzylabs/go-hubspot pull request #2
Opened 2021-11-10 15:17 UTC by OliverUrsell

Add support for the file api, including a function to upload a file to HubSpot and retrieve its link.

2021-11-11 06:58 UTC, d-lowl requested changes
Comments regarding the use of reflection, otherwise good to go

2021-11-11 06:58 UTC, d-lowl commented on file_test.go
> +				if !reflect.DeepEqual(expectedOptions, gotOptions) {
Should avoid reflection, and use `cmp.Equal` instead

2021-11-11 06:58 UTC, d-lowl commented on file_test.go
> +				if !reflect.DeepEqual(buf.Bytes(), fileContent) {
Same here, avoid reflection

2021-11-11 13:32 UTC, OliverUrsell commented on file_test.go
> +				if !reflect.DeepEqual(expectedOptions, gotOptions) {
Updated the use of reflection to use cmp

2021-11-11 13:33 UTC, OliverUrsell commented on file_test.go
> +				if !reflect.DeepEqual(buf.Bytes(), fileContent) {
See https://github.com/fuzzylabs/go-hubspot/pull/2#discussion_r747502085

2021-11-11 13:53 UTC, d-lowl approved these changes

2021-11-15 09:59 UTC, archena approved these changes

2021-11-15 11:25 UTC, merged